[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "plugin1"
version = "1.0"
description = "description of project1"

[project.entry-points."stevedore_testplugins.database"]
myplugin = "plugin1:myfunc2"